# Generated by Django 4.1.2 on 2022-10-07 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                ("context", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["event"], name="app_audit_event_ec8231_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["status"], name="app_audit_status_7debad_idx"),
        ),
    ]
